// Generated by CoffeeScript 2.7.0
(function() {
  var log, nordicCity;

  Array.prototype.first = function(amount) {
    if (amount === 1) {
      return this[0];
    } else {
      return this.slice(0, amount);
    }
  };

  Array.prototype.last = function(amount) {
    if (amount === 1) {
      return this[this.length - 1];
    } else {
      return this.slice(-amount);
    }
  };

  Array.prototype.random = function() {
    return this[Math.floor(Math.random() * this.length)];
  };

  // really just an easter egg; not practical at all
  Array.prototype.ninety_sixth = function() {
    return this[95];
  };

  // alias for join
  Array.prototype.reunite = function() {
    return this.join();
  };

  // the sum of all numbers in an array
  Array.prototype.sum = function() {
    return Number(this.join(''));
  };

  // returns true if the array is empty, false otherwise
  Array.prototype.empty = function() {
    return this.length === 0;
  };

  // returns true if the array is not empty, false otherwise
  Array.prototype.full = function() {
    return this.length === !0;
  };

  // convert seconds to milliseconds
  Number.prototype.in_milliseconds = function() {
    return this * 1000;
  };

  // convert milliseconds to seconds
  Number.prototype.in_seconds = function() {
    return Math.floor(this / 1000);
  };

  // set a timeout for the amount of milliseconds given
  Number.prototype.wait_for = function(ms) {
    return setTimeout(this, ms);
  };

  // alias for length
  String.prototype.characters = function() {
    return this.length;
  };

  // hide an element
  String.prototype.hide = function() {
    return document.getElementById(this).style.display = 'none';
  };

  // display and element
  String.prototype.display = function() {
    return document.getElementById(this).style.display = 'block';
  };

  // shorthand for document.getElementById
  String.prototype.get = function() {
    return document.getElementById(this);
  };

  // alias for console.log
  String.prototype.print = function() {
    return console.log(this);
  };

  // returns a random nordic city from Finland, Denmark, Sweden, Norway, or Iceland.
  nordicCity = function() {
    var cities;
    cities = ["Helsinki", "Tampere", "Lapland", "Malmö", "Örebro", "Sundsvall", "Trondheim", "Harstad", "Bergen", "Aarhus", "Holstebro", "Hirtshals", "Akureyri", "Reykjavik", "Selfoss"];
    return cities.random();
  };

  // alias for console.log
  log = function(message) {
    return console.log(message);
  };

}).call(this);

//# sourceMappingURL=fpcs_methods.js.map
