// Generated by CoffeeScript 2.7.0
(function() {
  // returns an array containing the first n amount of elements
  var indexOf = [].indexOf;

  Array.prototype.first = function(amount) {
    if (amount === 1) {
      return this[0];
    } else {
      return this.slice(0, amount);
    }
  };

  // returns an array containing the last n amount of elements
  Array.prototype.last = function(amount) {
    if (amount === 1) {
      return this[this.length - 1];
    } else {
      return this.slice(-amount);
    }
  };

  // returns a random element from your array
  Array.prototype.random = function() {
    return this[Math.floor(Math.random() * this.length)];
  };

  // really just an easter egg; not practical at all
  Array.prototype.ninety_sixth = function() {
    return this[95];
  };

  // alias for join
  Array.prototype.reunite = function() {
    return this.join();
  };

  // returns true if the array is empty, false otherwise
  Array.prototype.empty = function() {
    return this.length === 0;
  };

  // returns true if the array is not empty, false otherwise
  Array.prototype.full = function() {
    return this.length !== 0;
  };

  Array.prototype.includes = function(needle) {
    if (indexOf.call(this, needle) >= 0) {
      return true;
    } else {
      return false;
    }
  };

  // convert seconds to milliseconds
  Number.prototype.in_milliseconds = function() {
    return this * 1000;
  };

  // a more natural alias for Number.in_milliseconds. Similar to Number.seconds
  Number.prototype.milliseconds = function() {
    return this.in_milliseconds();
  };

  // convert milliseconds to seconds
  Number.prototype.in_seconds = function() {
    return Math.floor(this / 1000);
  };

  // set a timeout for the amount of milliseconds given
  Number.prototype.wait_for = function(callback) {
    return setTimeout(callback, this);
  };

  // executes a callback x amount of times.
  // example:
  // (3).times -> log "Savo"
  Number.prototype.times = function(callback) {
    var i, j, results;
    results = [];
    for (i = j = 0; (0 <= this ? j < this : j > this); i = 0 <= this ? ++j : --j) {
      results.push(callback(i));
    }
    return results;
  };

  // returns true if the given number is zero
  Number.prototype.zero = function() {
    if (this === 0) {
      return true;
    } else {
      return false;
    }
  };

  // doesn't do anything but makes some statements sound better
  // such as every (3).seconds -> console.log "something"
  Number.prototype.seconds = function() {
    return this.valueOf();
  };

  // (96).through(1704) -- returns an array of all numbers between 96 and 1704
  Number.prototype.through = function(number) {
    var array, iterator, j, ref;
    array = [];
    for (iterator = j = this, ref = number; (this <= ref ? j <= ref : j >= ref); iterator = this <= ref ? ++j : --j) {
      array.push(iterator);
    }
    return array;
  };

  // returns true if the number is even, false otherwise
  Number.prototype.is_even = function() {
    if (this % 2 === 0) {
      return true;
    } else {
      return false;
    }
  };

  // returns true if the number is odd, false otherwise
  Number.prototype.is_odd = function() {
    if (this.is_even() !== true) {
      return true;
    } else {
      return false;
    }
  };

  // checks if a number is between two numbers -- (1999).between(1704, 2004)
  Number.prototype.between = function(min, max) {
    if (this >= min && this <= max) {
      return true;
    } else {
      return false;
    }
  };

  // checks if a number is less than another number
  Number.prototype.less_than = function(number) {
    if (this < number) {
      return true;
    } else {
      return false;
    }
  };

  // checks if a number is greater than another number
  Number.prototype.greater_than = function(number) {
    if (this > number) {
      return true;
    } else {
      return false;
    }
  };

  // returns an array of the characters in the string
  String.prototype.characters = function() {
    return this.split("");
  };

  // get the lines from a string; split by newlines.
  // best when you just read a file and want to iterate over it by each line.
  String.prototype.lines = function() {
    return this.split("\n");
  };

  // alias for length
  String.prototype.character_count = function() {
    return this.length;
  };

  // hide an element
  String.prototype.hide = function() {
    return document.getElementById(this).style.display = 'none';
  };

  // display an element
  String.prototype.display = function() {
    return document.getElementById(this).style.display = 'block';
  };

  // shorthand for document.getElementById
  String.prototype.get = function() {
    return document.getElementById(this);
  };

  // alias for console.log
  String.prototype.print = function() {
    return console.log(this);
  };

  // capitalize a string
  String.prototype.upcase = function() {
    return this.toUpperCase();
  };

  // lowercase a string
  String.prototype.downcase = function() {
    return this.toLowerCase();
  };

  // returns true if the string is blank, false otherwise
  String.prototype.blank = function() {
    if (this.trim() === "") {
      return true;
    } else {
      return false;
    }
  };

  // returns true if a string is either of two given options.
  // usage: city.either("Helsinki", "Lahti")
  String.prototype.either = function(option_a, option_b) {
    if (this === option_a || this === option_b) {
      return true;
    } else {
      return false;
    }
  };

  // the opposite of String.either; returns true if the string is not either of the given options.
  String.prototype.isnt_either = function(option_a, option_b) {
    if (this !== option_a && this !== option_b) {
      return true;
    } else {
      return false;
    }
  };

  // returns a random nordic city from Finland, Denmark, Sweden, Norway, or Iceland.
  window.nordicCity = function() {
    var cities;
    cities = ["Helsinki", "Tampere", "Lapland", "Malmö", "Örebro", "Sundsvall", "Trondheim", "Harstad", "Bergen", "Aarhus", "Holstebro", "Hirtshals", "Akureyri", "Reykjavik", "Selfoss"];
    return cities.random();
  };

  // alias for console.log
  window.log = function(message) {
    return console.log(message);
  };

  // executes a callback every x seconds.
  // it is by no means required, but it is suggested to use it like this:
  // every (3).seconds -> log "Tampere"
  window.every = function(time, callback) {
    return setInterval(callback, time);
  };

}).call(this);

//# sourceMappingURL=fpcs_methods.js.map
