// Generated by CoffeeScript 2.7.0
(function() {
  // returns an array containing the first n amount of elements
  var log, nordicCity;

  Array.prototype.first = function(amount) {
    if (amount === 1) {
      return this[0];
    } else {
      return this.slice(0, amount);
    }
  };

  // returns an array containing the last n amount of elements
  Array.prototype.last = function(amount) {
    if (amount === 1) {
      return this[this.length - 1];
    } else {
      return this.slice(-amount);
    }
  };

  // returns a random element from your array
  Array.prototype.random = function() {
    return this[Math.floor(Math.random() * this.length)];
  };

  // really just an easter egg; not practical at all
  Array.prototype.ninety_sixth = function() {
    return this[95];
  };

  // alias for join
  Array.prototype.reunite = function() {
    return this.join();
  };

  // returns true if the array is empty, false otherwise
  Array.prototype.empty = function() {
    return this.length === 0;
  };

  // returns true if the array is not empty, false otherwise
  Array.prototype.full = function() {
    return this.length !== 0;
  };

  // convert seconds to milliseconds
  Number.prototype.in_milliseconds = function() {
    return this * 1000;
  };

  // convert milliseconds to seconds
  Number.prototype.in_seconds = function() {
    return Math.floor(this / 1000);
  };

  // set a timeout for the amount of milliseconds given
  Number.prototype.wait_for = function(callback) {
    return setTimeout(callback, this);
  };

  Number.prototype.times = function(callback) {
    var i, j, results;
    results = [];
    for (i = j = 0; (0 <= this ? j < this : j > this); i = 0 <= this ? ++j : --j) {
      results.push(callback(i));
    }
    return results;
  };

  Number.prototype.zero = function() {
    return this === 0;
  };

  // returns an array of the characters in the string
  String.prototype.characters = function() {
    return this.split("");
  };

  // alias for length
  String.prototype.character_count = function() {
    return this.length;
  };

  // hide an element
  String.prototype.hide = function() {
    return document.getElementById(this).style.display = 'none';
  };

  // display an element
  String.prototype.display = function() {
    return document.getElementById(this).style.display = 'block';
  };

  // shorthand for document.getElementById
  String.prototype.get = function() {
    return document.getElementById(this);
  };

  // alias for console.log
  String.prototype.print = function() {
    return console.log(this);
  };

  String.prototype.upcase = function() {
    return this.toUpperCase();
  };

  String.prototype.downcase = function() {
    return this.toLowerCase();
  };

  String.prototype.blank = function() {
    return this.length === 0;
  };

  // returns a random nordic city from Finland, Denmark, Sweden, Norway, or Iceland.
  nordicCity = function() {
    var cities;
    cities = ["Helsinki", "Tampere", "Lapland", "Malmö", "Örebro", "Sundsvall", "Trondheim", "Harstad", "Bergen", "Aarhus", "Holstebro", "Hirtshals", "Akureyri", "Reykjavik", "Selfoss"];
    return cities.random();
  };

  // alias for console.log
  log = function(message) {
    return console.log(message);
  };

}).call(this);

//# sourceMappingURL=fpcs_methods.js.map
